<a href="https://colab.research.google.com/github/i2mmmmm/train_project/blob/main/20230818_rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import LayerNormalization, MultiHeadAttention, Flatten
import tensorflow as tf
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, Activation
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping


In [2]:
from google.colab import drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
s30_trail = pd.read_csv('/content/drive/My Drive/철도/s30_trail.csv')
s40_trail = pd.read_csv('/content/drive/My Drive/철도/s40_trail.csv')
s50_trail = pd.read_csv('/content/drive/My Drive/철도/s50_trail.csv')
s70_trail = pd.read_csv('/content/drive/My Drive/철도/s70_trail.csv')
s100_trail = pd.read_csv('/content/drive/My Drive/철도/s100_trail.csv')
c30_trail = pd.read_csv('/content/drive/My Drive/철도/c30_trail.csv')
c40_trail = pd.read_csv('/content/drive/My Drive/철도/c40_trail.csv')
c50_trail = pd.read_csv('/content/drive/My Drive/철도/c50_trail.csv')
c70_trail = pd.read_csv('/content/drive/My Drive/철도/c70_trail.csv')
c100_trail = pd.read_csv('/content/drive/My Drive/철도/c100_trail.csv')


In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import LSTM, Flatten, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [31]:
c30_trail = c30_trail[['Curvature', 'A_M1_B1_BC_Y_L', 'A_M1_B1_W2_Y_L', 'A_M1_B1_BC_Y_R', 'A_M1_B1_W2_Y_R', 'A__B1_W1_Y_A_axle_L', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Y_A_axle_R', 'A__B1_W2_Y_A_axle_R',"YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"]]
c40_trail = c40_trail[['Curvature', 'A_M1_B1_BC_Y_L', 'A_M1_B1_W2_Y_L', 'A_M1_B1_BC_Y_R', 'A_M1_B1_W2_Y_R', 'A__B1_W1_Y_A_axle_L', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Y_A_axle_R', 'A__B1_W2_Y_A_axle_R',"YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"]]
c50_trail = c50_trail[['Curvature', 'A_M1_B1_BC_Y_L', 'A_M1_B1_W2_Y_L', 'A_M1_B1_BC_Y_R', 'A_M1_B1_W2_Y_R', 'A__B1_W1_Y_A_axle_L', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Y_A_axle_R', 'A__B1_W2_Y_A_axle_R',"YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"]]
c70_trail = c70_trail[['Curvature', 'A_M1_B1_BC_Y_L', 'A_M1_B1_W2_Y_L', 'A_M1_B1_BC_Y_R', 'A_M1_B1_W2_Y_R', 'A__B1_W1_Y_A_axle_L', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Y_A_axle_R', 'A__B1_W2_Y_A_axle_R',"YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"]]
c100_trail = c100_trail[['Curvature', 'A_M1_B1_BC_Y_L', 'A_M1_B1_W2_Y_L', 'A_M1_B1_BC_Y_R', 'A_M1_B1_W2_Y_R', 'A__B1_W1_Y_A_axle_L', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Y_A_axle_R', 'A__B1_W2_Y_A_axle_R',"YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"]]

s30_trail = s30_trail[['Curvature', 'A_M1_B1_BC_Y_L', 'A_M1_B1_W2_Y_L', 'A_M1_B1_BC_Y_R', 'A_M1_B1_W2_Y_R', 'A__B1_W1_Y_A_axle_L', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Y_A_axle_R', 'A__B1_W2_Y_A_axle_R',"YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"]]
s40_trail = s40_trail[['Curvature', 'A_M1_B1_BC_Y_L', 'A_M1_B1_W2_Y_L', 'A_M1_B1_BC_Y_R', 'A_M1_B1_W2_Y_R', 'A__B1_W1_Y_A_axle_L', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Y_A_axle_R', 'A__B1_W2_Y_A_axle_R',"YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"]]
s50_trail = s50_trail[['Curvature', 'A_M1_B1_BC_Y_L', 'A_M1_B1_W2_Y_L', 'A_M1_B1_BC_Y_R', 'A_M1_B1_W2_Y_R', 'A__B1_W1_Y_A_axle_L', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Y_A_axle_R', 'A__B1_W2_Y_A_axle_R',"YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"]]
s70_trail = s70_trail[['Curvature', 'A_M1_B1_BC_Y_L', 'A_M1_B1_W2_Y_L', 'A_M1_B1_BC_Y_R', 'A_M1_B1_W2_Y_R', 'A__B1_W1_Y_A_axle_L', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Y_A_axle_R', 'A__B1_W2_Y_A_axle_R',"YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"]]
s100_trail = s100_trail[['Curvature', 'A_M1_B1_BC_Y_L', 'A_M1_B1_W2_Y_L', 'A_M1_B1_BC_Y_R', 'A_M1_B1_W2_Y_R', 'A__B1_W1_Y_A_axle_L', 'A__B1_W2_Y_A_axle_L', 'A__B1_W1_Y_A_axle_R', 'A__B1_W2_Y_A_axle_R',"YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"]]

In [26]:
def prepare_data(filename):
    data = filename
    X = data.drop(columns=["YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"])
    y = data[["YL_M1_B1_W1", "YR_M1_B1_W1", "YL_M1_B1_W2", "YR_M1_B1_W2"]]

    # 데이터 스케일링 - 표준화
    scaler = StandardScaler()
    X = scaler.fit_transform(X)


    # # 데이터 정규화
    # scaler = MinMaxScaler()  # MinMaxScaler를 사용하여 데이터를 [0, 1] 범위로 정규화
    # X = scaler.fit_transform(X)

    return X, y

def reshape_data(X, y, N_TIMESTEPS):
    X_list, y_list = [], []
    X_padded = np.vstack([np.zeros((N_TIMESTEPS, X.shape[1])), X])

    for i in range(len(X_padded) - N_TIMESTEPS):
        X_list.append(X_padded[i:i+N_TIMESTEPS])
        y_list.append(y.iloc[i])

    return np.array(X_list), np.array(y_list)

data_s_X, data_s_y = prepare_data(c100_trail)

N_TIMESTEPS = 10
N_FEATURES = 34

X_s, y_s = reshape_data(data_s_X, data_s_y, N_TIMESTEPS)

# 트레이닝/테스트 데이터 나누기
X_train_s = X_s[:10001]
y_train_s = y_s[:10001]
X_test_s = X_s[10001:]
y_test_s = y_s[10001:]

# 모델 구축
inputs = tf.keras.Input(shape=(N_TIMESTEPS, N_FEATURES))

# Encoder: 3개의 LSTM 블록을 추가
x = LSTM(64, return_sequences=True)(inputs)
x = Dropout(0.5)(x)
x = LSTM(128, return_sequences=True)(x)
x = Dropout(0.5)(x)
x = LSTM(256, return_sequences=False)(x)
x = Dropout(0.5)(x)

# Fully Connected Layer로 디코딩
x = Dense(512, activation='relu')(x)
x = Dropout(0.5)(x)
outputs = Dense(4)(x)

model_rnn = Model(inputs=inputs, outputs=outputs)

model_rnn.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

# Early stopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=20)

# 모델 학습
model_rnn.fit(X_train_s, y_train_s, epochs=50, batch_size=64, validation_data=(X_test_s, y_test_s), callbacks=[es])

# 예측
predictions_s = model_rnn.predict(X_test_s)

# 예측 결과 출력
print("Predictions for data_s")
print(predictions_s[:5])


Epoch 1/50
157/157 [==============================] - 17s 80ms/step - loss: 5.6522e-04 - mae: 0.0171 - val_loss: 3.9632e-04 - val_mae: 0.0134
Epoch 2/50
157/157 [==============================] - 12s 74ms/step - loss: 2.3361e-04 - mae: 0.0115 - val_loss: 3.9731e-04 - val_mae: 0.0137
Epoch 3/50
157/157 [==============================] - 12s 74ms/step - loss: 1.8793e-04 - mae: 0.0104 - val_loss: 5.7284e-04 - val_mae: 0.0170
Epoch 4/50
157/157 [==============================] - 12s 74ms/step - loss: 1.6577e-04 - mae: 0.0097 - val_loss: 5.1367e-04 - val_mae: 0.0165
Epoch 5/50
157/157 [==============================] - 12s 78ms/step - loss: 1.5077e-04 - mae: 0.0092 - val_loss: 5.0070e-04 - val_mae: 0.0159
Epoch 6/50
157/157 [==============================] - 11s 72ms/step - loss: 1.4217e-04 - mae: 0.0089 - val_loss: 5.6813e-04 - val_mae: 0.0171
Epoch 7/50
157/157 [==============================] - 11s 71ms/step - loss: 1.3141e-04 - mae: 0.0086 - val_loss: 5.9697e-04 - val_mae: 0.0180
Epoch 

In [8]:
predictions_30s = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1', 'YL_M1_B1_W2', 'YR_M1_B1_W2'])

# CSV 파일로 저장
predictions_30s.to_csv('/content/drive/My Drive/철도/30s_20230818.csv', index=False)

In [10]:
predictions_50s = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1', 'YL_M1_B1_W2', 'YR_M1_B1_W2'])

# CSV 파일로 저장
predictions_50s.to_csv('/content/drive/My Drive/철도/50s_20230818.csv', index=False)

In [12]:
predictions_40s = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1', 'YL_M1_B1_W2', 'YR_M1_B1_W2'])

# CSV 파일로 저장
predictions_40s.to_csv('/content/drive/My Drive/철도/40s_20230818.csv', index=False)

In [14]:
predictions_70s = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1', 'YL_M1_B1_W2', 'YR_M1_B1_W2'])

# CSV 파일로 저장
predictions_70s.to_csv('/content/drive/My Drive/철도/70s_20230818.csv', index=False)

In [16]:
predictions_100s = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1', 'YL_M1_B1_W2', 'YR_M1_B1_W2'])

# CSV 파일로 저장
predictions_100s.to_csv('/content/drive/My Drive/철도/100s_20230818.csv', index=False)

In [19]:
predictions_30c = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1', 'YL_M1_B1_W2', 'YR_M1_B1_W2'])

# CSV 파일로 저장
predictions_30c.to_csv('/content/drive/My Drive/철도/30c_20230818.csv', index=False)

In [21]:
predictions_40c = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1', 'YL_M1_B1_W2', 'YR_M1_B1_W2'])

# CSV 파일로 저장
predictions_40c.to_csv('/content/drive/My Drive/철도/40c_20230818.csv', index=False)

In [23]:
predictions_50c = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1', 'YL_M1_B1_W2', 'YR_M1_B1_W2'])

# CSV 파일로 저장
predictions_50c.to_csv('/content/drive/My Drive/철도/50c_20230818.csv', index=False)

In [25]:
predictions_70c = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1', 'YL_M1_B1_W2', 'YR_M1_B1_W2'])

# CSV 파일로 저장
predictions_70c.to_csv('/content/drive/My Drive/철도/70c_20230818.csv', index=False)

In [27]:
predictions_100c = pd.DataFrame(predictions_s, columns=['YL_M1_B1_W1', 'YR_M1_B1_W1', 'YL_M1_B1_W2', 'YR_M1_B1_W2'])

# CSV 파일로 저장
predictions_100c.to_csv('/content/drive/My Drive/철도/100c_20230818.csv', index=False)

In [28]:
answer_sample = pd.read_csv('/content/drive/My Drive/철도/answer_sample.csv')
c30 = pd.read_csv('/content/drive/My Drive/철도/30c_20230818.csv')
c40 = pd.read_csv('/content/drive/My Drive/철도/40c_20230818.csv')
c50 = pd.read_csv('/content/drive/My Drive/철도/50c_20230818.csv')
c70 = pd.read_csv('/content/drive/My Drive/철도/70c_20230818.csv')
c100 = pd.read_csv('/content/drive/My Drive/철도/100c_20230818.csv')
s30 = pd.read_csv('/content/drive/My Drive/철도/30s_20230818.csv')
s40 = pd.read_csv('/content/drive/My Drive/철도/40s_20230818.csv')
s50 = pd.read_csv('/content/drive/My Drive/철도/50s_20230818.csv')
s70 = pd.read_csv('/content/drive/My Drive/철도/70s_20230818.csv')
s100 = pd.read_csv('/content/drive/My Drive/철도/100s_20230818.csv')

In [29]:
c30.columns = ['YL_M1_B1_W1_c30', 'YR_M1_B1_W1_c30', 'YL_M1_B1_W2_c30', 'YR_M1_B1_W2_c30']
c40.columns = ['YL_M1_B1_W1_c40', 'YR_M1_B1_W1_c40', 'YL_M1_B1_W2_c40', 'YR_M1_B1_W2_c40']
c50.columns = ['YL_M1_B1_W1_c50', 'YR_M1_B1_W1_c50', 'YL_M1_B1_W2_c50', 'YR_M1_B1_W2_c50']
c70.columns = ['YL_M1_B1_W1_c70', 'YR_M1_B1_W1_c70', 'YL_M1_B1_W2_c70', 'YR_M1_B1_W2_c70']
c100.columns = ['YL_M1_B1_W1_c100', 'YR_M1_B1_W1_c100', 'YL_M1_B1_W2_c100', 'YR_M1_B1_W2_c100']

s30.columns = ['YL_M1_B1_W1_s30', 'YR_M1_B1_W1_s30', 'YL_M1_B1_W2_s30', 'YR_M1_B1_W2_s30']
s40.columns = ['YL_M1_B1_W1_s40', 'YR_M1_B1_W1_s40', 'YL_M1_B1_W2_s40', 'YR_M1_B1_W2_s40']
s50.columns = ['YL_M1_B1_W1_s50', 'YR_M1_B1_W1_s50', 'YL_M1_B1_W2_s50', 'YR_M1_B1_W2_s50']
s70.columns = ['YL_M1_B1_W1_s70', 'YR_M1_B1_W1_s70', 'YL_M1_B1_W2_s70', 'YR_M1_B1_W2_s70']
s100.columns = ['YL_M1_B1_W1_s100', 'YR_M1_B1_W1_s100', 'YL_M1_B1_W2_s100', 'YR_M1_B1_W2_s100']

In [30]:
answer = pd.concat([answer_sample.Distance, s30,s40,s50,s70,s100,c30,c40,c50,c70,c100], axis=1)

In [31]:
answer

,Distance,YL_M1_B1_W1_s30,YR_M1_B1_W1_s30,YL_M1_B1_W2_s30,YR_M1_B1_W2_s30,YL_M1_B1_W1_s40,YR_M1_B1_W1_s40,YL_M1_B1_W2_s40,YR_M1_B1_W2_s40,YL_M1_B1_W1_s50,...,YL_M1_B1_W2_c50,YR_M1_B1_W2_c50,YL_M1_B1_W1_c70,YR_M1_B1_W1_c70,YL_M1_B1_W2_c70,YR_M1_B1_W2_c70,YL_M1_B1_W1_c100,YR_M1_B1_W1_c100,YL_M1_B1_W2_c100,YR_M1_B1_W2_c100
0,2500.25,0.025844,-0.010604,0.053779,-0.039806,-0.001595,0.008863,-0.006906,0.011805,-0.000634,...,0.001586,0.002153,0.001537,0.006674,-0.000376,0.004880,0.004037,0.005688,0.001202,0.004074
1,2500.50,0.025060,-0.008938,0.061642,-0.046519,-0.005713,0.012494,0.000452,0.003446,-0.004022,...,0.009022,-0.005109,-0.001641,0.009803,0.005552,-0.000801,0.001751,0.008168,0.009497,-0.003547
2,2500.75,0.021505,-0.005012,0.066962,-0.051955,-0.013299,0.019643,0.008820,-0.006839,-0.011360,...,0.016843,-0.012842,-0.007760,0.016179,0.012326,-0.007389,-0.003736,0.014196,0.018003,-0.011258
3,2501.00,0.015514,0.000397,0.066067,-0.052972,-0.020165,0.026271,0.013153,-0.012608,-0.017867,...,0.021594,-0.017524,-0.013751,0.022646,0.017574,-0.012356,-0.009902,0.021197,0.023059,-0.015712
4,2501.25,0.009298,0.006131,0.061756,-0.050829,-0.023032,0.029320,0.014599,-0.014321,-0.020007,...,0.023854,-0.019623,-0.016297,0.025504,0.021918,-0.016336,-0.013120,0.024946,0.026532,-0.018844
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,2998.75,0.013001,0.000827,0.042403,-0.032529,0.008050,0.000572,0.038136,-0.027770,0.008552,...,0.033407,-0.025734,0.011068,-0.003870,0.032999,-0.023315,0.009922,0.000191,0.034883,-0.025772
1995,2999.00,0.013082,0.000141,0.037244,-0.028002,0.009068,-0.000365,0.034778,-0.024845,0.010633,...,0.030550,-0.022900,0.011556,-0.004390,0.027528,-0.018467,0.010247,-0.000307,0.029498,-0.020909
1996,2999.25,0.011855,0.000351,0.026376,-0.018967,0.007189,0.000968,0.025829,-0.017773,0.007446,...,0.021864,-0.015258,0.008320,-0.000927,0.017934,-0.010512,0.007836,0.002174,0.020305,-0.013009
1997,2999.50,0.010450,0.000973,0.011992,-0.006894,0.006827,0.000888,0.012522,-0.006689,0.006634,...,0.010624,-0.005004,0.006846,0.001002,0.008070,-0.001805,0.006112,0.003870,0.009353,-0.003369


In [32]:
answer.to_csv('/content/drive/My Drive/철도/answer20230818.csv', index=False)

In [11]:
# 예측
predictions_s = model_rnn.predict(X_test_s)

# 예측 결과 출력
print("Predictions for data_s")
print(predictions_s[:5])

63/63 [==============================] - 3s 20ms/step
Predictions for data_s
[[ 0.01198157 -0.00319116 -0.00341078  0.0084604 ]
 [ 0.00600017  0.00297747  0.00071811  0.0045694 ]
 [ 0.00053653  0.00801952  0.00210619  0.00295452]
 [ 0.00104042  0.00773168  0.00760098 -0.0032873 ]
 [ 0.00427035  0.0050303   0.01482468 -0.01087351]]


In [12]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# 예측과 실제값 간의 MAE, MSE, RMSE, R-squared 계산
mae = mean_absolute_error(y_test_s, predictions_s)
mse = mean_squared_error(y_test_s, predictions_s)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_s, predictions_s)

# 결과 출력
print("Evaluation metrics for data_s:")
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R-squared:", r2)

#표준화1

Evaluation metrics for data_s:
MAE: 0.004768166674319996
MSE: 5.147999005504642e-05
RMSE: 0.007174955752828474
R-squared: 0.9037228458453308


In [14]:
# 예측
predictions_s2 = model_rnn.predict(X_test_s)

# 예측 결과 출력
print("Predictions for data_s")
print(predictions_s[:5])

63/63 [==============================] - 4s 36ms/step
Predictions for data_s
[[ 0.01198157 -0.00319116 -0.00341078  0.0084604 ]
 [ 0.00600017  0.00297747  0.00071811  0.0045694 ]
 [ 0.00053653  0.00801952  0.00210619  0.00295452]
 [ 0.00104042  0.00773168  0.00760098 -0.0032873 ]
 [ 0.00427035  0.0050303   0.01482468 -0.01087351]]


In [15]:

# 예측과 실제값 간의 MAE, MSE, RMSE, R-squared 계산
mae = mean_absolute_error(y_test_s, predictions_s2)
mse = mean_squared_error(y_test_s, predictions_s2)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_s, predictions_s2)

# 결과 출력
print("Evaluation metrics for data_s:")
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R-squared:", r2)

#표준화2

Evaluation metrics for data_s:
MAE: 0.004760738982342545
MSE: 4.877175403444326e-05
RMSE: 0.0069836776868955844
R-squared: 0.9040003756751076


In [18]:
# 예측
predictions_s3 = model_rnn.predict(X_test_s)

# 예측 결과 출력
print("Predictions for data_s")
print(predictions_s[:5])

63/63 [==============================] - 5s 39ms/step
Predictions for data_s
[[ 0.01198157 -0.00319116 -0.00341078  0.0084604 ]
 [ 0.00600017  0.00297747  0.00071811  0.0045694 ]
 [ 0.00053653  0.00801952  0.00210619  0.00295452]
 [ 0.00104042  0.00773168  0.00760098 -0.0032873 ]
 [ 0.00427035  0.0050303   0.01482468 -0.01087351]]


In [19]:
# 예측과 실제값 간의 MAE, MSE, RMSE, R-squared 계산
mae = mean_absolute_error(y_test_s, predictions_s3)
mse = mean_squared_error(y_test_s, predictions_s3)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_s, predictions_s3)

# 결과 출력
print("Evaluation metrics for data_s:")
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R-squared:", r2)

#표준화3

Evaluation metrics for data_s:
MAE: 0.004991263925108455
MSE: 5.57829655957259e-05
RMSE: 0.007468799474863808
R-squared: 0.8956848335741501


In [22]:
# 예측
predictions_s = model_rnn.predict(X_test_s)

# 예측 결과 출력
print("Predictions for data_s")
print(predictions_s[:5])

63/63 [==============================] - 4s 36ms/step
Predictions for data_s
[[ 0.00316528  0.00454689 -0.0141387   0.01971179]
 [-0.00441769  0.01236726 -0.01062775  0.0170127 ]
 [-0.00707417  0.01516715 -0.00811135  0.01464869]
 [-0.00360591  0.01103733  0.00228964  0.00330525]
 [ 0.00138989  0.00634703  0.01887827 -0.01423718]]


In [23]:
# 예측과 실제값 간의 MAE, MSE, RMSE, R-squared 계산
mae = mean_absolute_error(y_test_s, predictions_s3)
mse = mean_squared_error(y_test_s, predictions_s3)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_s, predictions_s3)

# 결과 출력
print("Evaluation metrics for data_s:")
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R-squared:", r2)

#정규화1

Evaluation metrics for data_s:
MAE: 0.004991263925108455
MSE: 5.57829655957259e-05
RMSE: 0.007468799474863808
R-squared: 0.8956848335741501


In [25]:
# 예측
predictions_s = model_rnn.predict(X_test_s)

# 예측 결과 출력
print("Predictions for data_s")
print(predictions_s[:5])

63/63 [==============================] - 4s 38ms/step
Predictions for data_s
[[ 0.00550468  0.00292676 -0.0111364   0.01755494]
 [-0.00244276  0.01039732 -0.0069253   0.01387212]
 [-0.00554051  0.01350192 -0.0037119   0.01080181]
 [-0.00247445  0.01016884  0.00651453 -0.00056151]
 [ 0.00081413  0.00691903  0.01958455 -0.01493562]]


In [26]:
# 예측과 실제값 간의 MAE, MSE, RMSE, R-squared 계산
mae = mean_absolute_error(y_test_s, predictions_s3)
mse = mean_squared_error(y_test_s, predictions_s3)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_s, predictions_s3)

# 결과 출력
print("Evaluation metrics for data_s:")
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R-squared:", r2)

#정규화2

Evaluation metrics for data_s:
MAE: 0.004991263925108455
MSE: 5.57829655957259e-05
RMSE: 0.007468799474863808
R-squared: 0.8956848335741501


In [28]:
# 예측
predictions_s = model_rnn.predict(X_test_s)

# 예측 결과 출력
print("Predictions for data_s")
print(predictions_s[:5])

63/63 [==============================] - 4s 37ms/step
Predictions for data_s
[[ 1.0254700e-02 -1.8531380e-03 -1.1785873e-02  1.5671097e-02]
 [ 4.2820526e-03  3.9641280e-03 -7.7994610e-03  1.3024660e-02]
 [ 2.3427792e-03  5.9662117e-03 -5.0421855e-03  1.0938298e-02]
 [ 6.4858501e-03  1.8518257e-03  5.5015073e-03 -7.4137002e-05]
 [ 9.5397942e-03 -3.8702204e-04  1.8501047e-02 -1.3374940e-02]]


In [29]:
# 예측과 실제값 간의 MAE, MSE, RMSE, R-squared 계산
mae = mean_absolute_error(y_test_s, predictions_s3)
mse = mean_squared_error(y_test_s, predictions_s3)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_s, predictions_s3)

# 결과 출력
print("Evaluation metrics for data_s:")
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R-squared:", r2)

#정규화3

Evaluation metrics for data_s:
MAE: 0.004991263925108455
MSE: 5.57829655957259e-05
RMSE: 0.007468799474863808
R-squared: 0.8956848335741501


In [35]:
# 예측
predictions_s = model_rnn.predict(X_test_s)

# 예측 결과 출력
print("Predictions for data_s")
print(predictions_s[:5])

63/63 [==============================] - 4s 22ms/step
Predictions for data_s
[[ 0.01038203 -0.0020693  -0.0049185   0.00951364]
 [ 0.00525536  0.00261569 -0.00101305  0.00576629]
 [ 0.00100307  0.00652749  0.00438935  0.00016659]
 [ 0.00286708  0.00495404  0.00774939 -0.0032901 ]
 [ 0.0052854   0.00316587  0.01175085 -0.00720569]]


In [36]:
# 예측과 실제값 간의 MAE, MSE, RMSE, R-squared 계산
mae = mean_absolute_error(y_test_s, predictions_s3)
mse = mean_squared_error(y_test_s, predictions_s3)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_s, predictions_s3)

# 결과 출력
print("Evaluation metrics for data_s:")
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R-squared:", r2)

Evaluation metrics for data_s:
MAE: 0.004991263925108455
MSE: 5.57829655957259e-05
RMSE: 0.007468799474863808
R-squared: 0.8956848335741501


In [ ]:
# 예측 결과 DataFrame 생성
predictions_df = pd.DataFrame(predictions_s, columns=["Pred_YL_M1_B1_W1", "Pred_YR_M1_B1_W1", "Pred_YL_M1_B1_W2", "Pred_YR_M1_B1_W2"])

# CSV로 저장
predictions_df.to_csv("/Users/leeyoungdong/predictions100.csv", index=False)